/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IpNftFactoryInterface extends ethers.utils.Interface {
  functions: {
    "IpNftContracts(address)": FunctionFragment;
    "getChildren()": FunctionFragment;
    "initialize()": FunctionFragment;
    "newLicensorContract(string,string,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "IpNftContracts",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getChildren",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "newLicensorContract",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "IpNftContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChildren",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "newLicensorContract",
    data: BytesLike
  ): Result;

  events: {
    "NewLicenseToken(address,address,string,string,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewLicenseToken"): EventFragment;
}

export class IpNftFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IpNftFactoryInterface;

  functions: {
    IpNftContracts(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    getChildren(overrides?: CallOverrides): Promise<[string[]]>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    newLicensorContract(
      IpBrandName: string,
      IpBrandSymbol: string,
      IpURI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  IpNftContracts(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  getChildren(overrides?: CallOverrides): Promise<string[]>;

  initialize(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  newLicensorContract(
    IpBrandName: string,
    IpBrandSymbol: string,
    IpURI: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    IpNftContracts(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    getChildren(overrides?: CallOverrides): Promise<string[]>;

    initialize(overrides?: CallOverrides): Promise<void>;

    newLicensorContract(
      IpBrandName: string,
      IpBrandSymbol: string,
      IpURI: string,
      overrides?: CallOverrides
    ): Promise<string[]>;
  };

  filters: {
    NewLicenseToken(
      IpNftContractAddress?: null,
      licensee?: null,
      IpBrandName?: null,
      IpBrandSymbol?: null,
      IpURI?: null
    ): TypedEventFilter<
      [string, string, string, string, string],
      {
        IpNftContractAddress: string;
        licensee: string;
        IpBrandName: string;
        IpBrandSymbol: string;
        IpURI: string;
      }
    >;
  };

  estimateGas: {
    IpNftContracts(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getChildren(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    newLicensorContract(
      IpBrandName: string,
      IpBrandSymbol: string,
      IpURI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    IpNftContracts(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getChildren(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    newLicensorContract(
      IpBrandName: string,
      IpBrandSymbol: string,
      IpURI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
